with source as (
    select
        company_root_cnpj,
        branch_order,
        check_digits,
        branch_type_code,
        trade_name,
        registration_status_code,
        registration_status_date,
        registration_status_reason_code,
        foreign_city_name,
        country_code,
        activity_start_date,
        primary_cnae_code,
        secondary_cnae_codes,
        street_type,
        street_name,
        address_number,
        address_complement,
        district,
        postal_code,
        state,
        municipality_code,
        area_code_1,
        phone_1,
        area_code_2,
        phone_2,
        fax_area_code,
        fax_number,
        email,
        special_status,
        special_status_date
    from {{ source('company_registry_raw', 'raw_company_registry_establishments') }}
),

standardized as (
    select
        lpad(nullif(trim(cast(company_root_cnpj as varchar)), ''), 8, '0') as company_root_cnpj,
        lpad(nullif(trim(cast(branch_order as varchar)), ''), 4, '0') as branch_order,
        lpad(nullif(trim(cast(check_digits as varchar)), ''), 2, '0') as check_digits,
        nullif(trim(cast(branch_type_code as varchar)), '') as branch_type_code,
        nullif(trim(cast(trade_name as varchar)), '') as trade_name,
        lpad(nullif(trim(cast(registration_status_code as varchar)), ''), 2, '0') as registration_status_code,
        try_strptime(nullif(trim(cast(registration_status_date as varchar)), ''), '%Y%m%d')::date as registration_status_date,
        lpad(nullif(trim(cast(registration_status_reason_code as varchar)), ''), 2, '0') as registration_status_reason_code,
        nullif(trim(cast(foreign_city_name as varchar)), '') as foreign_city_name,
        lpad(nullif(trim(cast(country_code as varchar)), ''), 3, '0') as country_code,
        try_strptime(nullif(trim(cast(activity_start_date as varchar)), ''), '%Y%m%d')::date as activity_start_date,
        lpad(nullif(trim(cast(primary_cnae_code as varchar)), ''), 7, '0') as primary_cnae_code,
        nullif(trim(cast(secondary_cnae_codes as varchar)), '') as secondary_cnae_codes,
        nullif(trim(cast(street_type as varchar)), '') as street_type,
        nullif(trim(cast(street_name as varchar)), '') as street_name,
        nullif(trim(cast(address_number as varchar)), '') as address_number,
        nullif(trim(cast(address_complement as varchar)), '') as address_complement,
        nullif(trim(cast(district as varchar)), '') as district,
        lpad(nullif(trim(cast(postal_code as varchar)), ''), 8, '0') as postal_code,
        upper(nullif(trim(cast(state as varchar)), '')) as state,
        lpad(nullif(trim(cast(municipality_code as varchar)), ''), 4, '0') as municipality_code,
        nullif(trim(cast(area_code_1 as varchar)), '') as area_code_1,
        nullif(trim(cast(phone_1 as varchar)), '') as phone_1,
        nullif(trim(cast(area_code_2 as varchar)), '') as area_code_2,
        nullif(trim(cast(phone_2 as varchar)), '') as phone_2,
        nullif(trim(cast(fax_area_code as varchar)), '') as fax_area_code,
        nullif(trim(cast(fax_number as varchar)), '') as fax_number,
        lower(nullif(trim(cast(email as varchar)), '')) as email,
        nullif(trim(cast(special_status as varchar)), '') as special_status,
        try_strptime(nullif(trim(cast(special_status_date as varchar)), ''), '%Y%m%d')::date as special_status_date
    from source
),

with_keys as (
    select
        company_root_cnpj || branch_order || check_digits as full_cnpj,
        company_root_cnpj,
        branch_order,
        check_digits,
        branch_type_code,
        trade_name,
        registration_status_code,
        registration_status_date,
        registration_status_reason_code,
        foreign_city_name,
        country_code,
        activity_start_date,
        primary_cnae_code,
        secondary_cnae_codes,
        street_type,
        street_name,
        address_number,
        address_complement,
        district,
        postal_code,
        state,
        municipality_code,
        area_code_1,
        phone_1,
        area_code_2,
        phone_2,
        fax_area_code,
        fax_number,
        email,
        special_status,
        special_status_date
    from standardized
)

select
    full_cnpj,
    company_root_cnpj,
    branch_order,
    check_digits,
    branch_type_code,
    trade_name,
    registration_status_code,
    registration_status_date,
    registration_status_reason_code,
    foreign_city_name,
    country_code,
    activity_start_date,
    primary_cnae_code,
    secondary_cnae_codes,
    street_type,
    street_name,
    address_number,
    address_complement,
    district,
    postal_code,
    state,
    municipality_code,
    area_code_1,
    phone_1,
    area_code_2,
    phone_2,
    fax_area_code,
    fax_number,
    email,
    special_status,
    special_status_date
from with_keys
where full_cnpj is not null
