with source as (
    select
        company_root_cnpj,
        branch_order,
        check_digits,
        branch_type_code,
        trade_name,
        registration_status_code,
        registration_status_date,
        registration_status_reason_code,
        foreign_city_name,
        country_code,
        activity_start_date,
        primary_cnae_code,
        secondary_cnae_codes,
        street_type,
        street_name,
        address_number,
        address_complement,
        district,
        postal_code,
        state,
        municipality_code,
        area_code_1,
        phone_1,
        area_code_2,
        phone_2,
        fax_area_code,
        fax_number,
        email,
        special_status,
        special_status_date
    from {{ source('company_registry_raw', 'raw_company_registry_establishments') }}
),

standardized as (
    select
        {{ standardize_code('company_root_cnpj', 8) }} as company_root_cnpj,
        {{ standardize_code('branch_order', 4) }} as branch_order,
        {{ standardize_code('check_digits', 2) }} as check_digits,
        {{ clean_text('branch_type_code') }} as branch_type_code,
        {{ clean_text('trade_name') }} as trade_name,
        {{ standardize_code('registration_status_code', 2) }} as registration_status_code,
        {{ parse_yyyymmdd_date('registration_status_date') }} as registration_status_date,
        {{ standardize_code('registration_status_reason_code', 2) }} as registration_status_reason_code,
        {{ clean_text('foreign_city_name') }} as foreign_city_name,
        {{ standardize_code('country_code', 3) }} as country_code,
        {{ parse_yyyymmdd_date('activity_start_date') }} as activity_start_date,
        {{ standardize_code('primary_cnae_code', 7) }} as primary_cnae_code,
        {{ clean_text('secondary_cnae_codes') }} as secondary_cnae_codes,
        {{ clean_text('street_type') }} as street_type,
        {{ clean_text('street_name') }} as street_name,
        {{ clean_text('address_number') }} as address_number,
        {{ clean_text('address_complement') }} as address_complement,
        {{ clean_text('district') }} as district,
        {{ standardize_code('postal_code', 8) }} as postal_code,
        {{ clean_text('state', 'upper') }} as state,
        {{ standardize_code('municipality_code', 4) }} as municipality_code,
        {{ clean_text('area_code_1') }} as area_code_1,
        {{ clean_text('phone_1') }} as phone_1,
        {{ clean_text('area_code_2') }} as area_code_2,
        {{ clean_text('phone_2') }} as phone_2,
        {{ clean_text('fax_area_code') }} as fax_area_code,
        {{ clean_text('fax_number') }} as fax_number,
        {{ clean_text('email', 'lower') }} as email,
        {{ clean_text('special_status') }} as special_status,
        {{ parse_yyyymmdd_date('special_status_date') }} as special_status_date
    from source
),

with_keys as (
    select
        company_root_cnpj || branch_order || check_digits as full_cnpj,
        company_root_cnpj,
        branch_order,
        check_digits,
        branch_type_code,
        trade_name,
        registration_status_code,
        registration_status_date,
        registration_status_reason_code,
        foreign_city_name,
        country_code,
        activity_start_date,
        primary_cnae_code,
        secondary_cnae_codes,
        street_type,
        street_name,
        address_number,
        address_complement,
        district,
        postal_code,
        state,
        municipality_code,
        area_code_1,
        phone_1,
        area_code_2,
        phone_2,
        fax_area_code,
        fax_number,
        email,
        special_status,
        special_status_date
    from standardized
)

select
    full_cnpj,
    company_root_cnpj,
    branch_order,
    check_digits,
    branch_type_code,
    trade_name,
    registration_status_code,
    registration_status_date,
    registration_status_reason_code,
    foreign_city_name,
    country_code,
    activity_start_date,
    primary_cnae_code,
    secondary_cnae_codes,
    street_type,
    street_name,
    address_number,
    address_complement,
    district,
    postal_code,
    state,
    municipality_code,
    area_code_1,
    phone_1,
    area_code_2,
    phone_2,
    fax_area_code,
    fax_number,
    email,
    special_status,
    special_status_date
from with_keys
where full_cnpj is not null
